
fastromfstool: fastromfstool.cpp ../src/ESP8266FastROMFS.cpp ../src/ESP8266FastROMFS.h
	g++ -g -Wall -o fastromfstool -DDEBUGFASTROMFS=0 fastromfstool.cpp ../src/ESP8266FastROMFS.cpp -I ../src

clean:
	rm -f fastromfstool
